### ISSUE TITLE
好像没有近战不挥拳(00958D81)

### ISSUE THREAD

**Issue by rongrong1000** [Willh92/079-ijl15#2]
screenshots/video about the resolution probloem here.
因为搜索一下 未找到这个地址 (00958D81)

**Comment by rongrong1000** [comment]
内存.写整数 (ids [i], 进制_十六到十 (“00958D81”), 2776862864)  ' 近战不挥拳

**Comment by rongrong1000** [comment]
``` c++
if (!Client::meleePunching) {
    byte meleePunching[] = { 0x00,0x5A,0x5A };
    Memory::WriteByteArray(0x00958D80, meleePunching, sizeof(meleePunching));
}
```

配置文件
meleePunching=true 近战会挥拳
meleePunching=false 攻击直接客户端崩了

**Comment by rongrong1000** [comment]
貌似第0个字节是 0x83
2776862864 -> A5 83 90 90

**Comment by long111d2** [comment]
支持ItemEff.img里头的特效(可用0xAA包头或ItemEffect激活) 括号里面什么意思 可以说下吗？
